# Generated by Django 5.2.9 on 2025-12-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='foto_referencia',
            field=models.ImageField(blank=True, null=True, upload_to='trabajos/'),
        ),
    ]
