# Generated by Django 5.2.9 on 2025-12-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_ordentrabajo_foto_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
    ]
