# Generated by Django 5.2.9 on 2025-12-19 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_ordentrabajo_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Observaciones / Complicaciones')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='avances/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='servicios.ordentrabajo')),
            ],
        ),
    ]
