# Generated by Django 6.0 on 2025-12-31 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_ordentrabajo_latitud_ordentrabajo_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='avances/')),
                ('avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='servicios.avance')),
            ],
        ),
    ]
