# Generated by Django 4.2.30 on 2026-05-01 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0007_fotoavance'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances', to=settings.AUTH_USER_MODEL),
        ),
    ]
