# Generated by Django 4.2.30 on 2026-08-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, verbose_name='Debe Cambiar Contraseña'),
        ),
    ]
