# Generated by Django 4.2.30 on 2026-08-27 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0011_crear_roles_y_estados_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código / SKU')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Ítem')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / Especificaciones')),
                ('tipo', models.CharField(choices=[('HERRAMIENTA', 'Herramienta / Equipo'), ('MATERIAL', 'Material / Consumible')], default='MATERIAL', max_length=20)),
                ('unidad_medida', models.CharField(default='Unidad', max_length=30, verbose_name='Unidad de Medida (ej. Metros, Unidades, Rollos)')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Stock Actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='Stock Mínimo de Alerta')),
                ('estado_herramienta', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'Dada de Baja')], default='DISPONIBLE', max_length=20, verbose_name='Estado de la Herramienta')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ítem de Inventario',
                'verbose_name_plural': 'Ítems de Inventario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada / Compra de Stock'), ('SALIDA_ORDEN', 'Salida por Orden de Trabajo'), ('AJUSTE', 'Ajuste Manual de Inventario'), ('DEVOLUCION', 'Devolución de Material')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_anterior', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_nuevo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='servicios.iteminventario')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='servicios.ordentrabajo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUsadoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_estimada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cantidad Estimada')),
                ('cantidad_real', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cantidad Consumida Real')),
                ('descontado_de_stock', models.BooleanField(default=False, verbose_name='¿Descontado del Stock?')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(limit_choices_to={'tipo': 'MATERIAL'}, on_delete=django.db.models.deletion.PROTECT, related_name='usos_ordenes', to='servicios.iteminventario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_usados', to='servicios.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Material Usado en Orden',
                'verbose_name_plural': 'Materiales Usados en Órdenes',
            },
        ),
        migrations.CreateModel(
            name='HerramientaAsignadaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devuelta', models.BooleanField(default=False, verbose_name='¿Herramienta Devuelta?')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones de Entrega/Devolución')),
                ('herramienta', models.ForeignKey(limit_choices_to={'tipo': 'HERRAMIENTA'}, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_ordenes', to='servicios.iteminventario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herramientas_asignadas', to='servicios.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Herramienta Asignada a Orden',
                'verbose_name_plural': 'Herramientas Asignadas a Órdenes',
            },
        ),
    ]
