# Generated by Django 4.2.30 on 2026-08-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_iteminventario_movimientoinventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramientaasignadaorden',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad Asignada'),
        ),
    ]
