# Generated by Django 4.2.30 on 2026-08-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0013_herramientaasignadaorden_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cedula',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cédula / Documento de Identidad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono de Contacto'),
        ),
    ]
