# Generated by Django 4.2.30 on 2026-08-29 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0014_profile_cedula_profile_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudInsumoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('MATERIAL', 'Material Consumible'), ('HERRAMIENTA', 'Herramienta')], default='MATERIAL', max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Solicitada')),
                ('motivo', models.TextField(verbose_name='Motivo / Justificación')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADA', 'Aprobada / Despachada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('observacion_resolucion', models.TextField(blank=True, default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_ordenes', to='servicios.iteminventario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_insumos', to='servicios.ordentrabajo')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_resueltos', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Insumo Adicional',
                'verbose_name_plural': 'Solicitudes de Insumos Adicionales',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
